import { Metadata } from 'next';
import { ThemeProvider } from 'next-themes';
import Book from '@/components/Common/Book/Book';
import '@styles/globals.css';
export const metadata: Metadata = {
  title: { template: '오늘의 책님 | %s', default: '오늘의 책님' },
  description: 'Generated by create next app',
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          disableTransitionOnChange
        >
          <Book>{children}</Book>
        </ThemeProvider>
      </body>
    </html>
  );
}
