import type { Metadata } from 'next';
import '@styles/globals.css';
import Book from '@/components/Home/Book/Book';
import { ThemeProvider } from 'next-themes';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <Book>{children}</Book>
        </ThemeProvider>
      </body>
    </html>
  );
}
